### ISSUE TITLE
Facebook link - tracking parameter breaks bakery link

### ISSUE THREAD

**Issue by Megslalk** [cakephp/bakery.cakephp.org#38]
FB recently started adding a "tracking" parameter to the end of links - breaking bakery links posted on Facebook (click throughs result in a 404 error)

i.e. https://bakery.cakephp.org/2018/10/24/cakephp_370RC1_released.html becomes https://bakery.cakephp.org/2018/10/24/cakephp_370RC1_released.html?fbclid=IwAR1dJEZFxirjVVNjhth8JX4DqTHL9Cin2KE8-7NUm-6aF3jctKayvaSjyng

**Comment by markstory** [comment]
Will be fixed in the next build.
